# Generated by Django 4.0.5 on 2022-07-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='provinsi',
        ),
    ]
